"use client";

import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import { cn } from "@/lib/utils";
import "../assets/global.scss";

import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from "react-hot-toast";
import ReduxProvider from "@/providers/ReduxProvider";

const inter = Noto_Sans({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReduxProvider>
      <GoogleOAuthProvider
        clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || ""}
      >
        <html lang="en" className="h-full">
          <body
            className={cn(
              "relative h-full font-sans antialiased",
              inter.className
            )}
          >
            <Toaster />
            <main className="relative flex flex-col min-h-screen">
              <div className="flex-grow flex-1">
                {children}

                {/* {isAuthorised() ? <AppLayout>{children}</AppLayout> : children} */}
              </div>
            </main>
          </body>
        </html>
      </GoogleOAuthProvider>
    </ReduxProvider>
  );
}
